### ISSUE TITLE
Migrate to ionic 7

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/users#84]
## What is the motivation for adding/enhancing this feature?
Migrating to ionic 7.x will help in using some latest features in the components and will also solve some issues that were present in ionic 6.

## What are the acceptance criteria?

- [ ] Update to ionic 7
- [ ] Migrate all the dependent package to a version that supports ionic 7
- [ ] Update the components as per the migration guide
- [ ] Test the components so that there is no breaking change

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
It has been observed that on refresh of users page the scrollbar is not working properly which is causing difficulty in searching the user.
Checked the same in production and found that it is working fine there.
Maybe it is occurring because of ionic upgrade.
Hence, reopening this ticket.
https://jam.dev/c/d6ea92f6-f249-429e-ba97-5cf475095712

**Comment by Adameddy26** [comment]
> It has been observed that on refresh of users page the scrollbar is not working properly which is causing difficulty in searching the user. Also the security group of logged in user is not properly aligned. Checked the same in production and found that it is working fine there. Maybe it is occurring because of ionic upgrade. Hence, reopening this ticket. https://jam.dev/c/d6ea92f6-f249-429e-ba97-5cf475095712 https://jam.dev/c/448b2ad2-0529-4a15-b73d-3e2052403426

Verified and working fine in release v1.10.0. Hence, closing this ticket.
https://jam.dev/c/d509ea47-26c1-469b-881b-a3db84a1ec9a
